POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2NjRjMDZiYmM4ZTdjOTYyYjIyMmRiZGUiLCJpYXQiOjE3MTYyNTg0OTUsImV4cCI6MTcxNjI2MjA5NX0.078ibxz_J1Etp2GfWeJE4gHl04sNvJFy-ka-ATGWlds

{
    "title": "Things are fine, people.",
    "author": "Matt Mansfield",
    "url": "google.com",
    "likes": 10
}