DELETE http://localhost:3003/api/blogs/664bead673f4c07f2d1df27b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2NjRiZDEwMjdkZjVmYWMzM2I5MmY0NGEiLCJpYXQiOjE3MTYyNTQwOTIsImV4cCI6MTcxNjI1NzY5Mn0.9w5JVx6iQuDVYxs7q5kQYqCxOmv5d32sNdMurrTP-Y0